# Generated by Django 3.1.6 on 2021-05-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210509_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('id',)},
        ),
    ]
